code --install-extension aaron-bond.better-comments
code --install-extension adpyke.codesnap
code --install-extension alefragnani.Bookmarks
code --install-extension alefragnani.project-manager
code --install-extension anseki.vscode-color
code --install-extension astro-build.astro-vscode
code --install-extension BeardedBear.beardedtheme
code --install-extension benjaminbenais.copilot-theme
code --install-extension BetaDv.discord-script-utilities
code --install-extension bmewburn.vscode-intelephense-client
code --install-extension bradlc.vscode-tailwindcss
code --install-extension burkeholland.simple-react-snippets
code --install-extension bytebots.discordjs-simplifier
code --install-extension cschlosser.doxdocgen
code --install-extension DaltonMenezes.aura-theme
code --install-extension DEVSENSE.composer-php-vscode
code --install-extension DEVSENSE.intelli-php-vscode
code --install-extension DEVSENSE.phptools-vscode
code --install-extension DEVSENSE.profiler-php-vscode
code --install-extension dracula-theme.theme-dracula
code --install-extension ecmel.vscode-html-css
code --install-extension EliverLara.andromeda
code --install-extension Equinusocio.vsc-community-material-theme
code --install-extension esbenp.prettier-vscode
code --install-extension file-icons.file-icons
code --install-extension formulahendry.auto-rename-tag
code --install-extension franneck94.c-cpp-runner
code --install-extension GitHub.remotehub
code --install-extension Gruntfuggly.todo-tree
code --install-extension GulajavaMinistudio.mayukaithemevsc
code --install-extension hoovercj.vscode-power-mode
code --install-extension icrawl.discord-vscode
code --install-extension jeff-hykin.better-cpp-syntax
code --install-extension johnpapa.vscode-peacock
code --install-extension johnpapa.winteriscoming
code --install-extension jprestidge.theme-material-theme
code --install-extension kaysonwu.cpptask
code --install-extension miguelsolorio.fluent-icons
code --install-extension ms-azuretools.vscode-docker
code --install-extension MS-CEINTL.vscode-language-pack-fr
code --install-extension MS-CEINTL.vscode-language-pack-ko
code --install-extension ms-dotnettools.csharp
code --install-extension ms-dotnettools.vscode-dotnet-runtime
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.jupyter
code --install-extension ms-vscode-remote.remote-wsl
code --install-extension ms-vscode.cmake-tools
code --install-extension ms-vscode.cpptools
code --install-extension ms-vscode.cpptools-extension-pack
code --install-extension ms-vscode.cpptools-themes
code --install-extension ms-vscode.makefile-tools
code --install-extension ms-vscode.powershell
code --install-extension ms-vscode.remote-repositories
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension oderwat.indent-rainbow
code --install-extension PKief.material-icon-theme
code --install-extension RobbOwen.synthwave-vscode
code --install-extension rust-lang.rust-analyzer
code --install-extension selfrefactor.niketa-theme
code --install-extension shalldie.background
code --install-extension shd101wyy.markdown-preview-enhanced
code --install-extension skyran.js-jsx-snippets
code --install-extension TabNine.tabnine-vscode
code --install-extension tal7aouy.icons
code --install-extension tal7aouy.rainbow-bracket
code --install-extension tinkertrain.theme-panda
code --install-extension tombonnike.vscode-status-bar-format-toggle
code --install-extension twxs.cmake
code --install-extension Tyriar.lorem-ipsum
code --install-extension uloco.theme-bluloco-dark
code --install-extension uloco.theme-bluloco-light
code --install-extension vadimcn.vscode-lldb
code --install-extension voldemortensen.rainbow-tags
code --install-extension WallabyJs.quokka-vscode
code --install-extension whizkydee.material-palenight-theme
code --install-extension zobo.php-intellisense